### ISSUE TITLE
Dependency versions

### ISSUE THREAD

**Issue by LeoStrange26** [jwkirchenbauer/lm-watermarking#14]
The demo presentation is not user-friendly for personal notebooks. It is desired to provide configuration instructions. Additionally, explicit documentation of environment dependencies, including versions, is requested.

**Comment by jwkirchenbauer** [comment]
Hi Leo,

I suggest you try installing the packages as specified in the `requirements.txt` file. If you find that the integration does not work with the current/latest versions of those packages please describe the specific issue you're having with a code example.

In terms of usage, I would look at this section of the README on [using the watermark processor and detector](https://github.com/jwkirchenbauer/lm-watermarking/tree/main#abstract-usage-of-the-watermarklogitsprocessor-and-watermarkdetector) in your own code. Generally our code and instructions assumes some familiarity with the popular Hugging Face `transformers` and `tokenizers` libraries as it is implemented as an integration for that ecosystem.
