### ISSUE TITLE
/experiments problems

### ISSUE THREAD

**Issue by LeoStrange26** [jwkirchenbauer/lm-watermarking#16]
while running the run_watermarking.py under /experiments, some problems occur:

RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

I wonder if you can fix it.

**Comment by jwkirchenbauer** [comment]
Hi again, could you provide some more information about what model and data you are trying to use? As well as maybe a snippet of the error.

There's no way to know for sure without more debugging, but in my experience, a common cause of a device side assert in huggingface language modeling code is from the embedding layer when you try to access the embedding vector for a token id that doesn't exist. This can happen when the embedding layer/model and the tokenizer aren't in agreement such as if you add a new token to the tokenizer but don't resize the embedding layer. 

I seem to remember an issue with this for the OPT or llama model but I am not sure. Again more information would be helpful.

**Comment by LeoStrange26** [comment]
well it is solved. thx

**Comment by d-stortion** [comment]
Hi! Could you tell me how did you solve that? I met the same problem.
