### ISSUE TITLE
HF demo link in README.md leads to a runtime error page

### ISSUE THREAD

**Issue by DamienAllonsius** [jwkirchenbauer/lm-watermarking#18]
The hugging face demo link in your README.md: https://huggingface.co/spaces/tomg-group-umd/lm-watermarking does not lead to a proper demo page:
<img width="1705" alt="Screenshot 2023-08-29 at 15 41 35" src="https://github.com/jwkirchenbauer/lm-watermarking/assets/11852475/33f6769f-b5c1-4519-9452-8731d401a452">

**Comment by jwkirchenbauer** [comment]
Hi! Sorry about that. I restarted the huggingface space, so you should be able to access it now.

Periodically, huggingface spaces seems to restart their serving machines or update other backend services, and we find that this causes an error in the front end from time to time.

**Comment by DamienAllonsius** [comment]
Thank you John. It seems to work now, I'm closing this issue.
(amazing paper btw, congratulations! 👏 )
