### ISSUE TITLE
Mismatch in vocab_size and scores Shape in WatermarkLogitsProcessor

### ISSUE THREAD

**Issue by Cooperx521** [jwkirchenbauer/lm-watermarking#23]
While debugging app.py (which uses the model 'facebook/opt-125m'), I encountered an issue in watermark_processor.py. In the __call__ method of the WatermarkLogitsProcessor class, the shape of the received scores parameter is torch.Size([1, 50272]). However, self.vocab_size is 50265. This discrepancy does not result in any errors, but it does affect the proportion of the G/R list splitting, and ideally, these values should be consistent.

**Comment by jwkirchenbauer** [comment]
Hi, so this mismatch is a bit of a "known issue" (at least to me) with how the huggingface transformers library OPT models are set up.

Basically, the model's tokenizer has one vocab size as configured by the library and the embedding layer of the model itself has has a different size, and it's not off by 1, as you can see, it's off by 7. The code in the first paper basically just handled this issue silently, only when it occurred, by ignoring or resampling something. It was a pretty rare thing where a token id pops up somewhere that is out of bounds.

Now, the llama models don't seem to have this mismatch, so I would recommend using those or any other language model family if this is causing an issue for you! Generally there isn't too much need to work with OPT anymore given the performance of newer models, in my opinion.
