### ISSUE TITLE
Inquiry

### ISSUE THREAD

**Issue by mars203030** [jwkirchenbauer/lm-watermarking#24]
Hi, does the proposed watermark works also with other models? how about llama2?

**Comment by jwkirchenbauer** [comment]
Yes! This should work with any huggingface transformers model, and llama2 is available through gated access here https://huggingface.co/meta-llama/Llama-2-7b-hf.

Generally, any huggingface transformers model that supports the `model.generate` function should work, but the strength and generation quality impact of the watermark at various `gamma` and `delta` settings will need to be empirically evaluated for the usecase you're considering (starting with the default parameter values is a good choice!).
