### ISSUE TITLE
Package Installation

### ISSUE THREAD

**Issue by ridhika123** [jwkirchenbauer/lm-watermarking#25]
Hi, I am trying to run the code run_watermark.py in the experiments folder. However, the modules associated with the library, watermark, does not import and it does not seem to exist. What can I do about this? Thanks!

**Comment by jwkirchenbauer** [comment]
Hi! 

The experiments directory is left there in association with the original paper's experiments for posterity, but is not the recommended starting point.

Rather, I suggest you make a small script in the root of the repository following the code demonstration shown in this part of the [README#how-to-use-the-watermark-in-your-own-code](https://github.com/jwkirchenbauer/lm-watermarking/tree/main#how-to-use-the-watermark-in-your-own-code).

If you need more help with this I can try and whip up a small working example.
