### ISSUE TITLE
Low GPU Utilization and Reduced Performance with Selfhash Watermarking on Vicuna-7b-v1.5-16k

### ISSUE THREAD

**Issue by Ardor-Wu** [jwkirchenbauer/lm-watermarking#32]
Hello,

I've noticed that the GPU utilization is around 25% when using the selfhash watermarking feature with vicuna-7b-v1.5-16k. This seems to result in a performance about 5 times slower compared to lefthash under identical context width settings. I am currently operating on a single H100 GPU. Could you provide any suggestions or insights on how to address this performance issue?

Thank you!

**Comment by JonasGeiping** [comment]
Hi!

This is just a consequence of our reference implementation (ab)using the CUDA PRNG and constantly reseeding it (https://github.com/jwkirchenbauer/lm-watermarking/blob/main/extended_watermark_processor.py#L69). For self-hash, this inefficiency is more pronounced, as all candidate tokens for the current position need to be checked, and this operation is not batched (see https://github.com/jwkirchenbauer/lm-watermarking/blob/5b0e207dca0576f6d77fe740f61a982944ba8460/extended_watermark_processor.py#L150C4-L150C4).

We did this mostly for compatibility reasons with our initial implementations. In principle, the computational effort of either left- or self-hash is neglible, compared to the computational effort of generating the next token. 

To deploy a more efficient implementation though, I would look at refactoring `_seed_rng` and/or `_get_greenlist_ids`  to use to a more efficient hash implementation. [This](https://github.com/julien-piet/cpp-hash) or [this](https://github.com/jwkirchenbauer/lm-watermarking/blob/5b0e207dca0576f6d77fe740f61a982944ba8460/alternative_prf_schemes.py#L159) might be relevant references to consult.
