### ISSUE TITLE
How to calculate AUC?

### ISSUE THREAD

**Issue by jiaocaicai** [jwkirchenbauer/lm-watermarking#34]
Hi,

When detecting text, the score dictionary is returned. The fields include `num_tokens_scored`, `num_green_tokens`, `green_fraction`, `z_score`, `p_value`, `z_score_at_T`, `prediction`, and `confidence`. When calculating AUC,  
 `metrics.roc_curve(all_pred, all_true, pos_label=1) ` 。

When the z_score of a text is greater than a threshold (for example, 4), we predict True. But `all_pred` is the probability of True. I don’t know how` all_pred` is understood and calculated in this paper.

Maybe this question is relatively simple, but I really don’t understand it. I look forward to your reply.

Thanks

**Comment by bupt01** [comment]
I'm having some confusion while calculating the ROC curve for watermark detection and would appreciate your help. Let's say we have 500 watermarked texts to calculate the detection accuracy. Should I calculate the false positive rate by selecting 500 original texts from the dataset, or should I use 500 texts generated by a large model without any watermark?
