### ISSUE TITLE
About the attacking code

### ISSUE THREAD

**Issue by LeoStrange26** [jwkirchenbauer/lm-watermarking#36]
Could you provide some Code implementing the T5 span attack mentioned in your paper?
(for beginners)

**Comment by jwkirchenbauer** [comment]
We suggest using the GPT based paraphrase attack detailed in [our second paper](https://arxiv.org/abs/2306.04634) over the T5 span replacement attack as this is much stronger and more realistic for present day attackers as well as benign users of API models for text writing and rewriting tasks.

If you are _particularly_ interested in T5 based attacks though, I can suggest a repository from a contemporary work from friends of ours also at UMD who also studied watermark reliability. They implement a T5 based attack, and their setup was designed to be run against our watermarking code, so this could be useful to you!
https://github.com/vinusankars/Reliability-of-AI-text-detectors
