### ISSUE TITLE
Not a common Model Type in transformers.

### ISSUE THREAD

**Issue by chenxin1996** [jwkirchenbauer/lm-watermarking#38]
I need to add a watermark to the large language model chatglm-6b from Tsinghua University. Unfortunately, the configuration file for chatglm-6b is in the ChatGLMConfig format, which is not a common model type in transformers. Therefore, I encounter an error: ValueError: Unrecognized configuration class <class 'transformers_modules.chatglm-6b.configuration_chatglm.ChatGLMConfig'> for this kind of AutoModel: AutoModelForCausalLM. Can you provide some suggestions to help resolve this issue?

**Comment by jwkirchenbauer** [comment]
Hmm. I'm not quite sure how to help with this. One thing to check is whether the ChatGLM model supports transformers `LogitsProcessor`'s as part of the generation config? This is how we originally applied the watermark to arbitrary huggingface models.

In recent months, the watermarking functionality has been added to upstream transformers as a first class argument to `model.generate` and so I'm wondering whether you can try using their implementation? Here are the docs on this feature: https://huggingface.co/docs/transformers/main/en/generation_strategies#watermarking
