### ISSUE TITLE
Figure 4 does not correspond to its caption

### ISSUE THREAD

**Issue by wjczf123** [jwkirchenbauer/lm-watermarking#39]
The caption writes '(c) The impact of the green list size parameter $\gamma$ on the z-score'. However, the figure looks like $\delta$.

**Comment by jwkirchenbauer** [comment]
Hi, thanks for the pointer! In a prior version of the figure we may have only shown variations on $\delta$ but in the camera copy the Fig. 4 shows 8 total settings, the cross of 2 values of $\gamma$ and 4 values of $\delta$.
