### ISSUE TITLE
Date for code release

### ISSUE THREAD

**Issue by arav-agarwal2** [jwkirchenbauer/lm-watermarking#4]
I do not want to be a bother - but as this paper has achieved some fame from ComputerPhile and whatnot, I personally am interested in seeing the code. As yesterday was the planned day of release, I wanted to just get a new date to check if this releases.

**Comment by jwkirchenbauer** [comment]
Hi!

No worries, we appreciate the interest! Currently leaning a bit on the `~`Feb 15th, I apologize, but the core code and demo should be out in the next few days, sorry for the delay.
