### ISSUE TITLE
About Experiments

### ISSUE THREAD

**Issue by jc-ryan** [jwkirchenbauer/lm-watermarking#5]
Hello there,

I just wanted to start by saying that I really appreciate your work! Your contributions are very valuable, and I've found your methods for detecting generated content from large models to be particularly insightful.

I was wondering if I could clarify something with you. Is it correct for me to assume that the code in the root directory is the polished version of the code in the experiments directory (e.g. experiments/watermark.py -> watermark_processor.py)? Additionally, if I wanted to replicate the main experiments mentioned in the paper, could you provide some guidance on the process?

Thank you so much for your time, and I look forward to hearing from you soon.

**Comment by jwkirchenbauer** [comment]
Hi!
Thanks for the kind words! I apologize that `experiments/README.md` is incomplete. What I can do is update the README with some high level run instructions.

I will also try and list a few key differences between the old "core" code, found in `experiments/watermark.py` and the updated `/watermark_processor.py`.  I refactored things a good deal, and the purpose of the experiments code is a pipeline for the paper, where as the refactored version is much more general, user friendly, and compact.

I am meaning to create a bit more of an end2end script for putting all the pieces together, but I can't really get to that right this minute. I'll leave this issue open and get back to you when I have pushed an updated readme in the `experiments` directory with some running instructions.

Thanks for your interest in the code!

**Comment by jc-ryan** [comment]
> Hi! Thanks for the kind words! I apologize that `experiments/README.md` is incomplete. What I can do is update the README with some high level run instructions.
> 
> I will also try and list a few key differences between the old "core" code, found in `experiments/watermark.py` and the updated `/watermark_processor.py`. I refactored things a good deal, and the purpose of the experiments code is a pipeline for the paper, where as the refactored version is much more general, user friendly, and compact.
> 
> I am meaning to create a bit more of an end2end script for putting all the pieces together, but I can't really get to that right this minute. I'll leave this issue open and get back to you when I have pushed an updated readme in the `experiments` directory with some running instructions.
> 
> Thanks for your interest in the code!

**Comment by jc-ryan** [comment]
Sorry I accidentally closed this issue, thanks for your response and for your willingness to update the README with instructions. Looking forward to seeing the update!

**Comment by jc-ryan** [comment]
Thanks for your response and for your willingness to update the README with instructions. Looking forward to seeing the update!

**Comment by jc-ryan** [comment]
Hello,

I had two more questions about the Conclusion section. Specifically, I was wondering what you meant by "possible robust hashing rules." Does this refer to improvements to the random number generator provided by torch? Also, what impact would improving the hashing rules have?

Additionally, I was curious about the differences between "a better way to deploy the model in a streaming context" and "a short span of watermarked text lives inside a longer non-watermarked span" compared to typical text. Would these differences create additional challenges for adding or detecting watermarks?

Thank you for your time and expertise!

**Comment by jwkirchenbauer** [comment]
Hi again, I have pushed an updated readme that describes how the code in the `experiments` dir works. I hope this is helpful! Feel free to reach out with specific questions if you're having trouble running things.
 
---
 
On the other followup questions:

1) One specific instance of a "robust hashing rule" we propose is "Algorithm 3 Robust Private Watermarking" from Section 5 in the paper (there are a few more details in Appendix D). While we discuss a few benefits in that section, one key consideration is propensity for "attack amplification" - one desires a scheme that minimizes the expected reduction in watermark strength for every token that an attacker corrupts. Unfortunately, a naive variant where more than one token is used (say $h$) to seed the hash function exhibits a behavior where for each token the attacker replaces, they modify $h$ lists seeded by that token, and add an expected $h/2$ red list tokens (they removed $h/2$ greens for the price of just $1$ token edit 😬 ). Algorithm 3 avoids this pitfall! When one token within the window $h$ preceding the index $i$ is changed by an attacker, the green/red lists at index $i$ only reshuffle with probability $1/h$, an improvement in robustness. We are currently evaluating it and other schemes in followup work.

2) Streaming considers the case where the input has unbounded token length and you want to estimate the watermark presence in an online manner. This is, in fact, itself related to this concept of considering sub-windows of the text when computing the watermark statistics. We think that windowing is an interesting, but potentially inelegant approach and are instead developing a scheme more natively suited to maintaining an estimate that treats the token index more like a discrete time dimension. We hope to have follow-up experiments out in the coming months so stay tuned! 🙂

**Comment by jc-ryan** [comment]
Thank you so much for your timely update and your patient response. Your help is greatly appreciated, and looking forward to your new progress~

Thanks again for your hard work and dedication to this project!

**Comment by jwkirchenbauer** [comment]
Feel free to open a new thread with any further questions about the code!
