### ISSUE TITLE
Attack experiment

### ISSUE THREAD

**Issue by 11asdad** [jwkirchenbauer/lm-watermarking#6]
Hi,

Your work is very impressive and I am extremely interested in it. I notice that you mentioned "Attack experiment code" in "Pending Items". I would like to know if you are already working on the attack and where I can follow up on your progress.

Thanks.

**Comment by jwkirchenbauer** [comment]
"Attack experiment code" refers to the experiments performed in Section 7.1. We plan to add some code to the `experiments` directory that demonstrates the T5 attack presented in the paper.

We are also working on a series of more robust detection algorithms in to be evaluated against an even more powerful attack - this repo is the best place to watch for updates on both fronts! Thanks for your interest!

**Comment by 11asdad** [comment]
Thank you for answering my question!
